/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Part4.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Part4.gltf')
  return (
    <group {...props} dispose={null}>
      {/* เพิ่มแสงในฉาก */}
      <ambientLight intensity={0.5} /> {/* แสงกระจายทั่วฉาก */}
      <directionalLight position={[5, 5, 5]} intensity={1.5} /> {/* จำลองแสงแดด */}
      <pointLight position={[-2, 2, -2]} intensity={2} color="white" /> {/* แหล่งกำเนิดแสงแบบจุด */}
      <mesh geometry={nodes.node.geometry} material={materials.DefaultMaterial} scale={0.02} position={[0,1,0]} >
      <meshStandardMaterial 
          color="#D3D3D3" 
          metalness={0.3} 
          roughness={0.3} 
          // flatShading={true} 
        />
        </mesh>
    </group>
  )
}

useGLTF.preload('/Part4.gltf')
